import { db } from '@/db';
import { applications } from '@/db/schema';

async function main() {
    const sampleApplications = [
        {
            firstName: 'Sarah',
            lastName: 'Chen',
            email: 'sarah.chen@email.com',
            phone: '(415) 123-4567',
            position: 'Software Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/sarah-chen.pdf',
            degree: "Master's",
            university: 'Stanford University',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2022,
            status: 'received',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Johnson',
            email: 'michael.johnson@email.com',
            phone: '(650) 234-5678',
            position: 'Frontend Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/michael-johnson.pdf',
            degree: "Bachelor's",
            university: 'UC Berkeley',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2021,
            status: 'received',
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            firstName: 'Emily',
            lastName: 'Rodriguez',
            email: 'emily.rodriguez@email.com',
            phone: '(408) 345-6789',
            position: 'Backend Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/emily-rodriguez.pdf',
            degree: "Master's",
            university: 'MIT',
            fieldOfStudy: 'Software Engineering',
            graduationYear: 2023,
            status: 'received',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            firstName: 'David',
            lastName: 'Kim',
            email: 'david.kim@email.com',
            phone: '(925) 456-7890',
            position: 'Full Stack Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/david-kim.pdf',
            degree: "Bachelor's",
            university: 'Carnegie Mellon University',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2020,
            status: 'received',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            firstName: 'Jessica',
            lastName: 'Williams',
            email: 'jessica.williams@email.com',
            phone: '(510) 567-8901',
            position: 'DevOps Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/jessica-williams.pdf',
            degree: 'PhD',
            university: 'Georgia Tech',
            fieldOfStudy: 'Information Technology',
            graduationYear: 2024,
            status: 'received',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            firstName: 'James',
            lastName: 'Anderson',
            email: 'james.anderson@email.com',
            phone: '(415) 678-9012',
            position: 'Data Scientist',
            resumeUrl: 'https://storage.veridia.io/resumes/james-anderson.pdf',
            degree: "Master's",
            university: 'Harvard University',
            fieldOfStudy: 'Data Science',
            graduationYear: 2022,
            status: 'under_review',
            createdAt: new Date('2024-11-10').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        {
            firstName: 'Amanda',
            lastName: 'Martinez',
            email: 'amanda.martinez@email.com',
            phone: '(650) 789-0123',
            position: 'Product Manager',
            resumeUrl: 'https://storage.veridia.io/resumes/amanda-martinez.pdf',
            degree: "Master's",
            university: 'Northwestern University',
            fieldOfStudy: 'Business Administration',
            graduationYear: 2019,
            status: 'under_review',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            firstName: 'Christopher',
            lastName: 'Taylor',
            email: 'christopher.taylor@email.com',
            phone: '(408) 890-1234',
            position: 'UI/UX Designer',
            resumeUrl: 'https://storage.veridia.io/resumes/christopher-taylor.pdf',
            degree: "Bachelor's",
            university: 'Rhode Island School of Design',
            fieldOfStudy: 'Design',
            graduationYear: 2021,
            status: 'under_review',
            createdAt: new Date('2024-11-13').toISOString(),
            updatedAt: new Date('2024-11-13').toISOString(),
        },
        {
            firstName: 'Nicole',
            lastName: 'Thomas',
            email: 'nicole.thomas@email.com',
            phone: '(925) 901-2345',
            position: 'QA Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/nicole-thomas.pdf',
            degree: "Bachelor's",
            university: 'University of Washington',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2020,
            status: 'under_review',
            createdAt: new Date('2024-11-14').toISOString(),
            updatedAt: new Date('2024-11-14').toISOString(),
        },
        {
            firstName: 'Daniel',
            lastName: 'Garcia',
            email: 'daniel.garcia@email.com',
            phone: '(510) 012-3456',
            position: 'Business Analyst',
            resumeUrl: 'https://storage.veridia.io/resumes/daniel-garcia.pdf',
            degree: "Master's",
            university: 'Columbia University',
            fieldOfStudy: 'Business Administration',
            graduationYear: 2018,
            status: 'interview_scheduled',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            firstName: 'Rachel',
            lastName: 'Lee',
            email: 'rachel.lee@email.com',
            phone: '(415) 123-5678',
            position: 'Software Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/rachel-lee.pdf',
            degree: "Bachelor's",
            university: 'University of Texas at Austin',
            fieldOfStudy: 'Software Engineering',
            graduationYear: 2022,
            status: 'interview_scheduled',
            createdAt: new Date('2024-11-06').toISOString(),
            updatedAt: new Date('2024-11-06').toISOString(),
        },
        {
            firstName: 'Kevin',
            lastName: 'Nguyen',
            email: 'kevin.nguyen@email.com',
            phone: '(650) 234-6789',
            position: 'Frontend Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/kevin-nguyen.pdf',
            degree: "Master's",
            university: 'University of Michigan',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2023,
            status: 'interview_scheduled',
            createdAt: new Date('2024-11-07').toISOString(),
            updatedAt: new Date('2024-11-07').toISOString(),
        },
        {
            firstName: 'Laura',
            lastName: 'Brown',
            email: 'laura.brown@email.com',
            phone: '(408) 345-7890',
            position: 'Backend Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/laura-brown.pdf',
            degree: 'PhD',
            university: 'Princeton University',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2024,
            status: 'interview_scheduled',
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            firstName: 'Robert',
            lastName: 'Wilson',
            email: 'robert.wilson@email.com',
            phone: '(925) 456-8901',
            position: 'Full Stack Developer',
            resumeUrl: 'https://storage.veridia.io/resumes/robert-wilson.pdf',
            degree: "Bachelor's",
            university: 'University of Illinois',
            fieldOfStudy: 'Information Technology',
            graduationYear: 2019,
            status: 'interview_scheduled',
            createdAt: new Date('2024-11-09').toISOString(),
            updatedAt: new Date('2024-11-09').toISOString(),
        },
        {
            firstName: 'Sophia',
            lastName: 'Moore',
            email: 'sophia.moore@email.com',
            phone: '(510) 567-9012',
            position: 'DevOps Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/sophia-moore.pdf',
            degree: "Master's",
            university: 'Purdue University',
            fieldOfStudy: 'Software Engineering',
            graduationYear: 2021,
            status: 'document_upload',
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },
        {
            firstName: 'Matthew',
            lastName: 'Davis',
            email: 'matthew.davis@email.com',
            phone: '(415) 678-0123',
            position: 'Data Scientist',
            resumeUrl: 'https://storage.veridia.io/resumes/matthew-davis.pdf',
            degree: 'PhD',
            university: 'Yale University',
            fieldOfStudy: 'Data Science',
            graduationYear: 2023,
            status: 'document_upload',
            createdAt: new Date('2024-11-02').toISOString(),
            updatedAt: new Date('2024-11-02').toISOString(),
        },
        {
            firstName: 'Olivia',
            lastName: 'Miller',
            email: 'olivia.miller@email.com',
            phone: '(650) 789-1234',
            position: 'Product Manager',
            resumeUrl: 'https://storage.veridia.io/resumes/olivia-miller.pdf',
            degree: "Bachelor's",
            university: 'Duke University',
            fieldOfStudy: 'Business Administration',
            graduationYear: 2020,
            status: 'document_upload',
            createdAt: new Date('2024-11-03').toISOString(),
            updatedAt: new Date('2024-11-03').toISOString(),
        },
        {
            firstName: 'Anthony',
            lastName: 'Jones',
            email: 'anthony.jones@email.com',
            phone: '(408) 890-2345',
            position: 'UI/UX Designer',
            resumeUrl: 'https://storage.veridia.io/resumes/anthony-jones.pdf',
            degree: "Master's",
            university: 'Parsons School of Design',
            fieldOfStudy: 'Design',
            graduationYear: 2022,
            status: 'final_decision',
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-10-28').toISOString(),
        },
        {
            firstName: 'Elizabeth',
            lastName: 'White',
            email: 'elizabeth.white@email.com',
            phone: '(925) 901-3456',
            position: 'QA Engineer',
            resumeUrl: 'https://storage.veridia.io/resumes/elizabeth-white.pdf',
            degree: "Bachelor's",
            university: 'Boston University',
            fieldOfStudy: 'Computer Science',
            graduationYear: 2021,
            status: 'final_decision',
            createdAt: new Date('2024-10-29').toISOString(),
            updatedAt: new Date('2024-10-29').toISOString(),
        },
        {
            firstName: 'Ryan',
            lastName: 'Harris',
            email: 'ryan.harris@email.com',
            phone: '(510) 012-4567',
            position: 'Business Analyst',
            resumeUrl: 'https://storage.veridia.io/resumes/ryan-harris.pdf',
            degree: "Master's",
            university: 'University of Southern California',
            fieldOfStudy: 'Business Administration',
            graduationYear: 2019,
            status: 'final_decision',
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-10-30').toISOString(),
        },
    ];

    await db.insert(applications).values(sampleApplications);
    
    console.log('✅ Applications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});