import { db } from '@/db';
import { workExperiences } from '@/db/schema';

async function main() {
    const sampleWorkExperiences = [
        // Application 1
        {
            applicationId: 1,
            position: 'Junior Software Engineer',
            company: 'Google',
            startDate: '2018-06',
            endDate: '2020-08',
            description: 'Developed backend services using Java and Spring Boot. Collaborated with cross-functional teams to deliver scalable solutions.',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            applicationId: 1,
            position: 'Software Engineer',
            company: 'Microsoft',
            startDate: '2020-09',
            endDate: 'Present',
            description: 'Leading development of cloud-native applications using React and Node.js. Mentoring junior developers and conducting code reviews.',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        // Application 2
        {
            applicationId: 2,
            position: 'Software Developer',
            company: 'Amazon',
            startDate: '2019-03',
            endDate: '2021-05',
            description: 'Built microservices architecture for e-commerce platform. Improved system performance by 40% through optimization.',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            applicationId: 2,
            position: 'Senior Software Developer',
            company: 'Apple',
            startDate: '2021-06',
            endDate: '2023-12',
            description: 'Led team of 5 developers in building iOS applications. Implemented CI/CD pipelines and automated testing frameworks.',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            applicationId: 2,
            position: 'Tech Lead',
            company: 'Meta',
            startDate: '2024-01',
            endDate: 'Present',
            description: 'Managing engineering team and architecting scalable social media features. Driving technical decisions and roadmap planning.',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        // Application 3
        {
            applicationId: 3,
            position: 'Frontend Developer',
            company: 'Netflix',
            startDate: '2017-09',
            endDate: '2020-02',
            description: 'Developed responsive web applications using React and Redux. Optimized streaming video player performance.',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            applicationId: 3,
            position: 'Senior Frontend Developer',
            company: 'Uber',
            startDate: '2020-03',
            endDate: 'Present',
            description: 'Building real-time mapping and tracking interfaces. Implementing advanced state management and performance optimization.',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        // Application 4
        {
            applicationId: 4,
            position: 'Backend Engineer',
            company: 'Airbnb',
            startDate: '2019-01',
            endDate: '2021-11',
            description: 'Designed and implemented RESTful APIs for booking system. Worked with PostgreSQL and Redis for data management.',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            applicationId: 4,
            position: 'Senior Backend Engineer',
            company: 'Stripe',
            startDate: '2021-12',
            endDate: 'Present',
            description: 'Building payment processing infrastructure handling millions of transactions. Ensuring PCI compliance and security standards.',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        // Application 5
        {
            applicationId: 5,
            position: 'Full Stack Developer',
            company: 'Shopify',
            startDate: '2018-04',
            endDate: '2020-09',
            description: 'Developed e-commerce features using Ruby on Rails and React. Integrated third-party payment and shipping APIs.',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            applicationId: 5,
            position: 'Senior Full Stack Developer',
            company: 'Adobe',
            startDate: '2020-10',
            endDate: 'Present',
            description: 'Building creative cloud applications with modern web technologies. Leading architecture decisions for scalable SaaS products.',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        // Application 6
        {
            applicationId: 6,
            position: 'Junior Developer',
            company: 'Oracle',
            startDate: '2019-07',
            endDate: '2021-03',
            description: 'Developed enterprise database solutions using Java and PL/SQL. Participated in agile development processes.',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            applicationId: 6,
            position: 'Software Engineer',
            company: 'Salesforce',
            startDate: '2021-04',
            endDate: '2023-08',
            description: 'Built CRM features and integrations using Apex and Lightning Web Components. Improved customer data processing efficiency.',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            applicationId: 6,
            position: 'Senior Software Engineer',
            company: 'IBM',
            startDate: '2023-09',
            endDate: 'Present',
            description: 'Leading cloud infrastructure projects and AI integration initiatives. Mentoring team members on best practices.',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        // Application 7
        {
            applicationId: 7,
            position: 'Software Developer',
            company: 'Intel',
            startDate: '2018-08',
            endDate: '2021-01',
            description: 'Developed embedded systems software for IoT devices. Optimized code for performance on resource-constrained hardware.',
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            applicationId: 7,
            position: 'Senior Software Developer',
            company: 'Tesla',
            startDate: '2021-02',
            endDate: 'Present',
            description: 'Building autonomous vehicle software and in-car entertainment systems. Working on real-time processing and ML algorithms.',
            createdAt: new Date('2024-01-21').toISOString(),
        },
        // Application 8
        {
            applicationId: 8,
            position: 'Backend Developer',
            company: 'SpaceX',
            startDate: '2019-05',
            endDate: '2022-04',
            description: 'Developed mission control systems and telemetry processing applications. Ensured high reliability and fault tolerance.',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            applicationId: 8,
            position: 'Senior Backend Developer',
            company: 'Twitter',
            startDate: '2022-05',
            endDate: 'Present',
            description: 'Building distributed systems for social media platform handling millions of users. Optimizing database queries and caching strategies.',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        // Application 9
        {
            applicationId: 9,
            position: 'Frontend Engineer',
            company: 'LinkedIn',
            startDate: '2017-11',
            endDate: '2020-06',
            description: 'Built professional networking features using React and TypeScript. Implemented responsive design and accessibility standards.',
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            applicationId: 9,
            position: 'Senior Frontend Engineer',
            company: 'Dropbox',
            startDate: '2020-07',
            endDate: '2023-02',
            description: 'Developed file sharing and collaboration tools. Led migration to modern frontend architecture and improved performance.',
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            applicationId: 9,
            position: 'Staff Engineer',
            company: 'Slack',
            startDate: '2023-03',
            endDate: 'Present',
            description: 'Architecting real-time messaging infrastructure and API design. Driving technical excellence across engineering organization.',
            createdAt: new Date('2024-01-23').toISOString(),
        },
        // Application 10
        {
            applicationId: 10,
            position: 'Software Engineer',
            company: 'Zoom',
            startDate: '2018-10',
            endDate: '2021-09',
            description: 'Developed video conferencing features and WebRTC implementations. Optimized bandwidth usage and video quality.',
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            applicationId: 10,
            position: 'Senior Software Engineer',
            company: 'Atlassian',
            startDate: '2021-10',
            endDate: 'Present',
            description: 'Building project management and collaboration tools. Implementing integrations with third-party services and APIs.',
            createdAt: new Date('2024-01-24').toISOString(),
        },
        // Application 11
        {
            applicationId: 11,
            position: 'DevOps Engineer',
            company: 'GitHub',
            startDate: '2019-02',
            endDate: '2021-12',
            description: 'Managed CI/CD pipelines and infrastructure automation. Deployed containerized applications using Kubernetes and Docker.',
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            applicationId: 11,
            position: 'Senior DevOps Engineer',
            company: 'GitLab',
            startDate: '2022-01',
            endDate: 'Present',
            description: 'Leading platform engineering initiatives and cloud infrastructure design. Implementing observability and monitoring solutions.',
            createdAt: new Date('2024-01-25').toISOString(),
        },
        // Application 12
        {
            applicationId: 12,
            position: 'Mobile Developer',
            company: 'Google',
            startDate: '2018-03',
            endDate: '2020-11',
            description: 'Developed Android applications using Kotlin and Jetpack Compose. Implemented material design principles and accessibility features.',
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            applicationId: 12,
            position: 'Senior Mobile Developer',
            company: 'Apple',
            startDate: '2020-12',
            endDate: '2023-06',
            description: 'Built iOS applications using Swift and SwiftUI. Led adoption of MVVM architecture and unit testing practices.',
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            applicationId: 12,
            position: 'Mobile Tech Lead',
            company: 'Meta',
            startDate: '2023-07',
            endDate: 'Present',
            description: 'Managing cross-platform mobile development team. Architecting shared code libraries and development standards.',
            createdAt: new Date('2024-01-26').toISOString(),
        },
        // Application 13
        {
            applicationId: 13,
            position: 'Data Engineer',
            company: 'Amazon',
            startDate: '2019-04',
            endDate: '2022-01',
            description: 'Built data pipelines using Apache Spark and Airflow. Processed and analyzed petabytes of customer data.',
            createdAt: new Date('2024-01-27').toISOString(),
        },
        {
            applicationId: 13,
            position: 'Senior Data Engineer',
            company: 'Netflix',
            startDate: '2022-02',
            endDate: 'Present',
            description: 'Designing data architecture for recommendation systems. Implementing real-time data processing with Kafka and Flink.',
            createdAt: new Date('2024-01-27').toISOString(),
        },
        // Application 14
        {
            applicationId: 14,
            position: 'Full Stack Engineer',
            company: 'Uber',
            startDate: '2018-07',
            endDate: '2021-04',
            description: 'Developed rider and driver applications using React Native and Node.js. Implemented geolocation features and real-time tracking.',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            applicationId: 14,
            position: 'Senior Full Stack Engineer',
            company: 'Airbnb',
            startDate: '2021-05',
            endDate: 'Present',
            description: 'Building booking platform and host management tools. Leading frontend architecture and API design decisions.',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        // Application 15
        {
            applicationId: 15,
            position: 'Software Engineer',
            company: 'Stripe',
            startDate: '2019-08',
            endDate: '2022-03',
            description: 'Developed payment APIs and fraud detection systems. Ensured high availability and security compliance.',
            createdAt: new Date('2024-01-29').toISOString(),
        },
        {
            applicationId: 15,
            position: 'Senior Software Engineer',
            company: 'Shopify',
            startDate: '2022-04',
            endDate: 'Present',
            description: 'Building merchant tools and checkout experiences. Implementing A/B testing framework and analytics integration.',
            createdAt: new Date('2024-01-29').toISOString(),
        },
        // Application 16
        {
            applicationId: 16,
            position: 'Backend Developer',
            company: 'Adobe',
            startDate: '2018-05',
            endDate: '2020-10',
            description: 'Developed document processing services and cloud storage solutions. Optimized file conversion and rendering performance.',
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            applicationId: 16,
            position: 'Senior Backend Developer',
            company: 'Oracle',
            startDate: '2020-11',
            endDate: '2023-05',
            description: 'Built enterprise database management systems and cloud infrastructure. Led migration projects from on-premise to cloud.',
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            applicationId: 16,
            position: 'Principal Engineer',
            company: 'Salesforce',
            startDate: '2023-06',
            endDate: 'Present',
            description: 'Defining technical strategy and architecture for CRM platform. Driving innovation and engineering excellence initiatives.',
            createdAt: new Date('2024-01-30').toISOString(),
        },
        // Application 17
        {
            applicationId: 17,
            position: 'Cloud Engineer',
            company: 'Microsoft',
            startDate: '2019-09',
            endDate: '2022-02',
            description: 'Managed Azure cloud infrastructure and serverless applications. Implemented auto-scaling and cost optimization strategies.',
            createdAt: new Date('2024-01-31').toISOString(),
        },
        {
            applicationId: 17,
            position: 'Senior Cloud Engineer',
            company: 'Google',
            startDate: '2022-03',
            endDate: 'Present',
            description: 'Architecting GCP solutions for enterprise clients. Building infrastructure as code using Terraform and implementing security best practices.',
            createdAt: new Date('2024-01-31').toISOString(),
        },
        // Application 18
        {
            applicationId: 18,
            position: 'Machine Learning Engineer',
            company: 'Tesla',
            startDate: '2018-12',
            endDate: '2021-07',
            description: 'Developed computer vision models for autonomous driving. Trained deep learning models using PyTorch and TensorFlow.',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            applicationId: 18,
            position: 'Senior ML Engineer',
            company: 'Meta',
            startDate: '2021-08',
            endDate: 'Present',
            description: 'Building recommendation systems and content ranking algorithms. Deploying ML models at scale serving billions of users.',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        // Application 19
        {
            applicationId: 19,
            position: 'Security Engineer',
            company: 'Intel',
            startDate: '2019-06',
            endDate: '2022-01',
            description: 'Implemented security protocols and vulnerability assessments. Developed intrusion detection systems and encryption solutions.',
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            applicationId: 19,
            position: 'Senior Security Engineer',
            company: 'Apple',
            startDate: '2022-02',
            endDate: 'Present',
            description: 'Leading security architecture for consumer products. Conducting penetration testing and security audits.',
            createdAt: new Date('2024-02-02').toISOString(),
        },
        // Application 20
        {
            applicationId: 20,
            position: 'Site Reliability Engineer',
            company: 'LinkedIn',
            startDate: '2018-09',
            endDate: '2021-05',
            description: 'Maintained 99.99% uptime for production systems. Implemented monitoring, alerting, and incident response procedures.',
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            applicationId: 20,
            position: 'Senior SRE',
            company: 'Dropbox',
            startDate: '2021-06',
            endDate: '2023-11',
            description: 'Managed distributed storage infrastructure and disaster recovery systems. Automated operations and reduced MTTR by 60%.',
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            applicationId: 20,
            position: 'Staff SRE',
            company: 'Slack',
            startDate: '2023-12',
            endDate: 'Present',
            description: 'Architecting reliability engineering practices across organization. Leading incident management and post-mortem processes.',
            createdAt: new Date('2024-02-03').toISOString(),
        },
    ];

    await db.insert(workExperiences).values(sampleWorkExperiences);
    
    console.log('✅ Work experiences seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});